title: Hello, world! I'm Carlos McCray
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Carlos McCray # add your name
author-img: carlos-mccray.jpg # add your photo
about-author: I’ve been in Information Technology consultancy and management since 2002 wearing many hats since then such as being a senior engineer, running a field team, running a project management office, process improvement manager, and a director of service delivery.  I have a passion in all things automation and absolutely love making technology do things that were once done by a human.  I am currently exploring Azure and recycling of plastics with my kids. # add description
social-twitter: carlosmccray15 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: anitalex # add your Github handle
social-linkedin: carlosmccray47 # add your Linkedin handle
social-email: carlos.mccray@live.com # add your Email address

# Disqus
discus-identifier: carlosmccray # add your discus identifier

# Tracker
analytics: G-Z7YKFDL9BL # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
